[2020-01-30 13:18:46,803] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-01-30 13:28:46,808] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-01-30 13:38:46,817] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-01-30 13:48:46,839] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-01-30 13:52:40,292] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2020-01-30 13:52:40,297] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2020-01-30 13:52:40,299] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2020-01-30 13:52:40,310] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-console-consumer-90439-1-2e9601af-9962-49a3-8acd-523dc2abc90f] in group console-consumer-90439 has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-01-30 13:52:40,312] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-90439 in state PreparingRebalance with old generation 1 (__consumer_offsets-26) (reason: removing member consumer-console-consumer-90439-1-2e9601af-9962-49a3-8acd-523dc2abc90f on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2020-01-30 13:52:40,313] INFO [GroupCoordinator 0]: Group console-consumer-90439 with generation 2 is now empty (__consumer_offsets-26) (kafka.coordinator.group.GroupCoordinator)
[2020-01-30 13:52:40,648] WARN Session 0x100001544610000 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:363)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)
[2020-01-30 13:52:40,756] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2020-01-30 13:52:40,756] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient)
[2020-01-30 13:52:41,918] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-01-30 13:52:41,920] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-01-30 13:52:42,025] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2020-01-30 13:52:43,149] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-01-30 13:52:43,149] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-01-30 13:52:45,030] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-01-30 13:52:45,031] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-01-30 13:52:46,952] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-01-30 13:52:46,953] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-01-30 13:52:47,427] INFO Terminating process due to signal SIGTERM (org.apache.kafka.common.utils.LoggingSignalHandler)
[2020-01-30 13:52:48,358] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-01-30 13:52:48,358] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-01-30 13:52:48,927] INFO [GroupCoordinator 0]: Member rdkafka-7f8542f9-1539-4e7f-a546-4f762d6285b0 in group myGroup has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-01-30 13:52:48,927] INFO [GroupCoordinator 0]: Preparing to rebalance group myGroup in state PreparingRebalance with old generation 1 (__consumer_offsets-17) (reason: removing member rdkafka-7f8542f9-1539-4e7f-a546-4f762d6285b0 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2020-01-30 13:52:48,928] INFO [GroupCoordinator 0]: Group myGroup with generation 2 is now empty (__consumer_offsets-17) (kafka.coordinator.group.GroupCoordinator)
[2020-01-30 13:52:50,207] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-01-30 13:52:50,208] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
